# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: /home/zhangfeng/tangjh/oth/dataset
#data_dir: /home/tangjh/dataset/ts_ctx_data # # #F:\programs\dataset
#data_dir: /mnt/mlc1/tjh/dataset
stats_path: ${paths.root_dir}/stats_multi.json

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to logging directory
log_dir: ${paths.root_dir}/ts_context_logs/${exp_main.name}

# path to working directory
work_dir: ${hydra:runtime.cwd}